# Generated by Django 3.2.7 on 2021-09-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='acceptDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_address', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=50)),
                ('accept', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='driverDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('vehical_name', models.CharField(max_length=100)),
                ('vehical_number', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('driver_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='waitingDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
            ],
        ),
    ]
