# Generated by Django 3.2.6 on 2021-08-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideether', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('vehical_name', models.CharField(max_length=100)),
                ('vehical_number', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
